"""Driver psychological profiles, team economics, and power unit supply data."""

PU_SUPPLIERS = {
    "mercedes": {
        "name": "Mercedes-AMG High Performance Powertrains",
        "hq": "Brixworth, UK",
        "teams": ["mercedes", "mclaren", "williams", "alpine"],
        "team_names": ["Mercedes", "McLaren", "Williams", "Alpine"],
        "color": "#00d2be",
        "years_in_f1": "1994-present (as Ilmor/Mercedes)",
        "titles_pu": 15,
        "notable": "Dominant hybrid-era supplier (2014-2021). Supplies 4 of 11 teams — the largest customer base on the grid. Alpine switched from Renault to Mercedes for 2026.",
    },
    "ferrari": {
        "name": "Scuderia Ferrari Power Unit",
        "hq": "Maranello, Italy",
        "teams": ["ferrari", "haas", "cadillac"],
        "team_names": ["Ferrari", "Haas", "Cadillac"],
        "color": "#dc143c",
        "years_in_f1": "1950-present",
        "titles_pu": 16,
        "notable": "The oldest and most successful F1 constructor. Supplies Cadillac's customer PU for their first two seasons (2026-2027) until GM develops its own unit.",
    },
    "red_bull_ford": {
        "name": "Red Bull Powertrains / Ford",
        "hq": "Milton Keynes, UK",
        "teams": ["red_bull", "rb"],
        "team_names": ["Red Bull", "Racing Bulls"],
        "color": "#3671C6",
        "years_in_f1": "2026-present (RBPT); Ford returning after 2004",
        "titles_pu": 0,
        "notable": "Brand-new PU operation. Red Bull built its own engine facility after Honda's initial departure. Ford partnership adds branding, funding, and some engineering. First in-house Red Bull power unit.",
    },
    "honda": {
        "name": "Honda Racing Corporation",
        "hq": "Sakura, Japan",
        "teams": ["aston_martin"],
        "team_names": ["Aston Martin"],
        "color": "#006f62",
        "years_in_f1": "1964-1968, 1983-1992, 2000-2008, 2015-2021, 2026-present",
        "titles_pu": 6,
        "notable": "Returned to F1 as works supplier for Aston Martin. Previously powered Red Bull to 2021-2022 titles. Exclusive single-team partnership — no customer teams.",
    },
    "audi": {
        "name": "Audi Formula Racing GmbH",
        "hq": "Neuburg an der Donau, Germany",
        "teams": ["audi"],
        "team_names": ["Audi"],
        "color": "#00e701",
        "years_in_f1": "2026-present",
        "titles_pu": 0,
        "notable": "Volkswagen Group entry. Acquired Sauber as factory team. Developing PU in-house. The MGU-H deletion was a key factor enabling their entry — it removed the most complex component that new manufacturers couldn't catch up on.",
    },
}

TEAM_BUDGETS = {
    "mercedes": {"budget_m": 135, "staff": 1000, "factory": "Brackley, UK"},
    "ferrari": {"budget_m": 135, "staff": 1100, "factory": "Maranello, Italy"},
    "red_bull": {"budget_m": 135, "staff": 950, "factory": "Milton Keynes, UK"},
    "mclaren": {"budget_m": 135, "staff": 900, "factory": "Woking, UK"},
    "aston_martin": {"budget_m": 135, "staff": 850, "factory": "Silverstone, UK"},
    "alpine": {"budget_m": 130, "staff": 800, "factory": "Enstone/Viry, UK/France"},
    "williams": {"budget_m": 120, "staff": 750, "factory": "Grove, UK"},
    "haas": {"budget_m": 115, "staff": 400, "factory": "Kannapolis, USA / Maranello"},
    "rb": {"budget_m": 125, "staff": 700, "factory": "Faenza, Italy"},
    "audi": {"budget_m": 130, "staff": 600, "factory": "Hinwil, Switzerland"},
    "sauber": {"budget_m": 130, "staff": 600, "factory": "Hinwil, Switzerland"},
    "cadillac": {"budget_m": 110, "staff": 350, "factory": "Silverstone, UK (new)"},
}

CIRCUIT_TYPES = {
    "albert_park": {"type": "street-park", "power": 0.5, "downforce": 0.6, "overtaking": 0.5},
    "shanghai": {"type": "permanent", "power": 0.7, "downforce": 0.5, "overtaking": 0.7},
    "suzuka": {"type": "permanent", "power": 0.6, "downforce": 0.9, "overtaking": 0.3},
    "miami": {"type": "street-park", "power": 0.6, "downforce": 0.5, "overtaking": 0.6},
    "monaco": {"type": "street", "power": 0.2, "downforce": 0.9, "overtaking": 0.1},
    "silverstone": {"type": "permanent", "power": 0.7, "downforce": 0.8, "overtaking": 0.6},
    "spa": {"type": "permanent", "power": 0.8, "downforce": 0.7, "overtaking": 0.7},
    "monza": {"type": "permanent", "power": 0.95, "downforce": 0.2, "overtaking": 0.8},
    "singapore": {"type": "street", "power": 0.3, "downforce": 0.8, "overtaking": 0.3},
    "interlagos": {"type": "permanent", "power": 0.6, "downforce": 0.6, "overtaking": 0.7},
    "jeddah": {"type": "street", "power": 0.8, "downforce": 0.5, "overtaking": 0.5},
    "bahrain": {"type": "permanent", "power": 0.6, "downforce": 0.6, "overtaking": 0.6},
    "red_bull_ring": {"type": "permanent", "power": 0.7, "downforce": 0.5, "overtaking": 0.5},
    "hungaroring": {"type": "permanent", "power": 0.3, "downforce": 0.8, "overtaking": 0.2},
    "zandvoort": {"type": "permanent", "power": 0.4, "downforce": 0.7, "overtaking": 0.3},
    "baku": {"type": "street", "power": 0.8, "downforce": 0.4, "overtaking": 0.6},
    "americas": {"type": "permanent", "power": 0.6, "downforce": 0.7, "overtaking": 0.6},
    "las_vegas": {"type": "street", "power": 0.8, "downforce": 0.4, "overtaking": 0.6},
    "losail": {"type": "permanent", "power": 0.7, "downforce": 0.6, "overtaking": 0.5},
    "yas_marina": {"type": "permanent", "power": 0.5, "downforce": 0.6, "overtaking": 0.5},
    "imola": {"type": "permanent", "power": 0.5, "downforce": 0.7, "overtaking": 0.3},
    "barcelona": {"type": "permanent", "power": 0.6, "downforce": 0.7, "overtaking": 0.4},
    "portimao": {"type": "permanent", "power": 0.6, "downforce": 0.6, "overtaking": 0.5},
}

DRIVER_PROFILES = {
    "antonelli": {
        "archetype": "The Prodigy",
        "big5": {"openness": 85, "conscientiousness": 70, "extraversion": 60, "agreeableness": 65, "neuroticism": 30},
        "driving_style": "Smooth, precise, instinctive. Exceptional car control from karting pedigree. Makes complex maneuvers look effortless. Adapts to conditions faster than peers — his wet-weather FP2 at Monza 2024 was the moment Mercedes committed.",
        "risk_profile": "Calculated risk-taker. Pushes limits in qualifying but races with maturity beyond his years. Low crash rate relative to pace.",
        "team_dynamics": "Thrives as lead driver. Respectful of Russell but clearly the faster driver from race one. No ego conflicts — focused inward.",
        "traits": {"aggression": 65, "consistency": 80, "wet_ability": 90, "tire_mgmt": 75, "qualifying": 90, "racecraft": 80},
    },
    "russell": {
        "archetype": "The Analyst",
        "big5": {"openness": 70, "conscientiousness": 90, "extraversion": 75, "agreeableness": 55, "neuroticism": 35},
        "driving_style": "Methodical, data-driven, technically exceptional. Maximizes every situation. Known for extracting pace from difficult positions and exceptional tire management.",
        "risk_profile": "Strategic risk management. Picks battles carefully. Will sacrifice a position now to gain later. Occasionally overdrives when frustrated.",
        "team_dynamics": "Natural team leader. Strong communicator, politically astute within the paddock. Handles being second driver with professional grace.",
        "traits": {"aggression": 55, "consistency": 85, "wet_ability": 75, "tire_mgmt": 90, "qualifying": 85, "racecraft": 75},
    },
    "leclerc": {
        "archetype": "The Romantic",
        "big5": {"openness": 90, "conscientiousness": 65, "extraversion": 55, "agreeableness": 70, "neuroticism": 50},
        "driving_style": "Emotional, raw pace in qualifying. Beautiful one-lap speed but historically prone to strategic missteps and team miscommunication. The artist who can produce moments of brilliance.",
        "risk_profile": "High-risk, high-reward. Will attempt overtakes others wouldn't. Occasionally costly — Imola 2022, France 2022. But the upside is electric.",
        "team_dynamics": "Comfortable as team leader at Ferrari. Deep emotional bond with the team and Maranello. Can be frustrated by team strategy calls.",
        "traits": {"aggression": 75, "consistency": 65, "wet_ability": 70, "tire_mgmt": 65, "qualifying": 95, "racecraft": 70},
    },
    "norris": {
        "archetype": "The Perfectionist",
        "big5": {"openness": 80, "conscientiousness": 85, "extraversion": 70, "agreeableness": 75, "neuroticism": 55},
        "driving_style": "Technically gifted with exceptional smoothness. Manages tires brilliantly and excels in changing conditions. Has overcome early-career tendency to crack under championship pressure.",
        "risk_profile": "Conservative in wheel-to-wheel but fast in clear air. The 2025 championship showed he can handle pressure. Start-line performance historically weak but improving.",
        "team_dynamics": "Strong partnership with McLaren. Loyal, well-integrated. Constructive feedback loop with engineers. Healthy competition with Piastri.",
        "traits": {"aggression": 50, "consistency": 85, "wet_ability": 85, "tire_mgmt": 90, "qualifying": 85, "racecraft": 70},
    },
    "hamilton": {
        "archetype": "The Legend",
        "big5": {"openness": 75, "conscientiousness": 80, "extraversion": 65, "agreeableness": 60, "neuroticism": 40},
        "driving_style": "Adaptive genius. Has reinvented his driving style multiple times across eras. Exceptional in the wet, legendary overtaker, supreme tire management. In his 20th season — reflexes marginally slower but racecraft unmatched.",
        "risk_profile": "Mature risk assessment from 20 years of experience. Knows when to push and when to bank points. Rarely makes unforced errors at this stage.",
        "team_dynamics": "The mentoring phase. At Ferrari to win a championship with the Scuderia — the last great challenge. Relationship with Leclerc is respectful but competitive.",
        "traits": {"aggression": 60, "consistency": 80, "wet_ability": 95, "tire_mgmt": 95, "qualifying": 80, "racecraft": 95},
    },
    "piastri": {
        "archetype": "The Ice Man",
        "big5": {"openness": 55, "conscientiousness": 90, "extraversion": 35, "agreeableness": 50, "neuroticism": 20},
        "driving_style": "Cold, clinical efficiency. Rarely makes mistakes, rarely produces highlight-reel moments. Wins by being faster, not flashier. Reminiscent of peak Räikkönen — just gets the job done.",
        "risk_profile": "Low emotional variance. Doesn't get rattled, doesn't get euphoric. Consistent performance regardless of circumstances. This is his superpower.",
        "team_dynamics": "Independent. Doesn't need team politics or emotional support. Professional relationship with Norris — respects the hierarchy but will challenge when faster.",
        "traits": {"aggression": 45, "consistency": 92, "wet_ability": 70, "tire_mgmt": 80, "qualifying": 80, "racecraft": 75},
    },
    "max_verstappen": {
        "archetype": "The Apex Predator",
        "big5": {"openness": 60, "conscientiousness": 75, "extraversion": 45, "agreeableness": 30, "neuroticism": 25},
        "driving_style": "Aggressive, uncompromising, supernaturally fast. Brakes later, turns in harder, and exits faster than anyone. In a lesser car in 2026, the raw speed is still visible but results don't follow.",
        "risk_profile": "Famously aggressive in wheel-to-wheel combat. 'I'm not here to finish second.' Will push the rules to their absolute limit. The stewards know him by name.",
        "team_dynamics": "Demands the team build around him. In 2026, Red Bull's car isn't competitive enough — this creates visible frustration. Loyalty to Red Bull is being tested.",
        "traits": {"aggression": 95, "consistency": 80, "wet_ability": 90, "tire_mgmt": 75, "qualifying": 90, "racecraft": 90},
    },
    "bearman": {
        "archetype": "The Grinder",
        "big5": {"openness": 65, "conscientiousness": 85, "extraversion": 50, "agreeableness": 70, "neuroticism": 35},
        "driving_style": "Dependable, mature beyond his years. Proved himself with exceptional substitute drives in 2024. Extracts maximum from midfield machinery. Strong race pace, improving qualifying.",
        "risk_profile": "Conservative for his age. Understands that finishing is scoring. Builds confidence through consistent results rather than heroic moves.",
        "team_dynamics": "Low-maintenance driver. Gives clear feedback, doesn't create drama. The kind of driver team principals love working with.",
        "traits": {"aggression": 50, "consistency": 75, "wet_ability": 65, "tire_mgmt": 70, "qualifying": 65, "racecraft": 70},
    },
    "gasly": {
        "archetype": "The Survivor",
        "big5": {"openness": 70, "conscientiousness": 75, "extraversion": 65, "agreeableness": 60, "neuroticism": 45},
        "driving_style": "Quick and committed. Rebuilt his career after the traumatic Red Bull demotion. Best in high-speed corners where commitment matters. Sometimes lacks pace in slow-speed sections.",
        "risk_profile": "Measured aggression. Lost close friend Anthoine Hubert at Spa 2019 — this shapes his risk calculus. Pushes hard but knows the limits.",
        "team_dynamics": "Natural team leader at Alpine. Brings experience and development direction. Good relationship with Colapinto.",
        "traits": {"aggression": 60, "consistency": 70, "wet_ability": 65, "tire_mgmt": 70, "qualifying": 75, "racecraft": 70},
    },
    "lawson": {
        "archetype": "The Dark Horse",
        "big5": {"openness": 65, "conscientiousness": 80, "extraversion": 55, "agreeableness": 50, "neuroticism": 30},
        "driving_style": "Aggressive debut style that drew Verstappen comparisons. Strong racecraft, willing to fight for position. Raw and occasionally rough around the edges but the speed is genuine.",
        "risk_profile": "High aggression tempered by a calm demeanor. Doesn't get flustered in combat. The broken hand at Zandvoort 2023 showed his toughness.",
        "team_dynamics": "Comfortable as the junior in the Red Bull system. Learning rapidly. Political skills still developing.",
        "traits": {"aggression": 75, "consistency": 65, "wet_ability": 60, "tire_mgmt": 60, "qualifying": 70, "racecraft": 75},
    },
    "colapinto": {
        "archetype": "The Showman",
        "big5": {"openness": 85, "conscientiousness": 60, "extraversion": 90, "agreeableness": 75, "neuroticism": 45},
        "driving_style": "Flamboyant, emotional, fast. Burst onto the scene at Williams 2024 with stunning pace. Occasionally pushes too hard — the crashes at Las Vegas and Brazil 2024. Raw talent with rough edges.",
        "risk_profile": "High risk tolerance. The Argentine passion is real — hero or zero. Maturing in 2026 but still prone to spectacular incidents.",
        "team_dynamics": "Massive fanbase (Argentine F1 renaissance). Brings energy and sponsorship. Alpine sees long-term potential if discipline improves.",
        "traits": {"aggression": 80, "consistency": 55, "wet_ability": 55, "tire_mgmt": 55, "qualifying": 70, "racecraft": 65},
    },
    "arvid_lindblad": {
        "archetype": "The Rookie",
        "big5": {"openness": 70, "conscientiousness": 75, "extraversion": 45, "agreeableness": 65, "neuroticism": 35},
        "driving_style": "The youngest driver on the grid at 18. Red Bull junior with exceptional junior formula results. Still adapting to F1 machinery. Flashes of speed interspersed with learning moments.",
        "risk_profile": "Learning risk calibration in real-time. Protected by team expectations — no pressure to deliver immediately. Growing race by race.",
        "team_dynamics": "Absorbing everything from the Red Bull ecosystem. Paired with Lawson as mentor figure at RB.",
        "traits": {"aggression": 55, "consistency": 55, "wet_ability": 50, "tire_mgmt": 50, "qualifying": 65, "racecraft": 55},
    },
    "hadjar": {
        "archetype": "The Calculator",
        "big5": {"openness": 60, "conscientiousness": 85, "extraversion": 40, "agreeableness": 55, "neuroticism": 30},
        "driving_style": "Cerebral approach to racing. Excellent at reading races and making positions through strategy rather than brute force. Strong in F2, adapting to F1 pace requirements.",
        "risk_profile": "Calculated. Prefers to race with his head rather than his heart. Rarely makes contact-related errors.",
        "team_dynamics": "Quiet, professional. Let his results speak. Comfortable in the Red Bull environment despite the pressure.",
        "traits": {"aggression": 40, "consistency": 75, "wet_ability": 60, "tire_mgmt": 70, "qualifying": 65, "racecraft": 70},
    },
    "sainz": {
        "archetype": "The Warrior",
        "big5": {"openness": 55, "conscientiousness": 90, "extraversion": 60, "agreeableness": 45, "neuroticism": 40},
        "driving_style": "Relentless competitor. Never gives up a position without a fight. Excellent race pace and tire management. Qualifying sometimes a weakness but extracts maximum on Sundays.",
        "risk_profile": "Will drive through pain (raced at Jeddah 2022 with appendicitis aftermath). Never backs down. Carries the weight of being dropped from Ferrari with visible determination.",
        "team_dynamics": "Brings intensity and competitiveness to Williams. A catalyst for team improvement. Demanding but fair with engineers.",
        "traits": {"aggression": 70, "consistency": 80, "wet_ability": 70, "tire_mgmt": 85, "qualifying": 70, "racecraft": 80},
    },
    "bortoleto": {
        "archetype": "The Scholar",
        "big5": {"openness": 75, "conscientiousness": 80, "extraversion": 65, "agreeableness": 70, "neuroticism": 35},
        "driving_style": "Intelligent racer with strong junior credentials (F2 champion). Methodical approach to learning the F1 car. Good feedback to engineers. Speed is building gradually.",
        "risk_profile": "Patient. Understands the long game. Won't overdrive a car that isn't capable of more. Learns from mistakes quickly.",
        "team_dynamics": "Good relationship with Hulkenberg as experienced teammate. Brazilian passion contained by German-Swiss team culture at Audi.",
        "traits": {"aggression": 45, "consistency": 70, "wet_ability": 60, "tire_mgmt": 65, "qualifying": 60, "racecraft": 65},
    },
    "ocon": {
        "archetype": "The Contrarian",
        "big5": {"openness": 50, "conscientiousness": 70, "extraversion": 40, "agreeableness": 35, "neuroticism": 55},
        "driving_style": "Defensive master. Exceptional at holding position against faster cars. Strong in the wet. Can produce stunning results (Hungary 2021 win) when everything aligns.",
        "risk_profile": "Defensive driving occasionally tips into over-aggression. History of teammate conflicts (Perez, Gasly, Alonso). Guards his position fiercely.",
        "team_dynamics": "Complex history with teammates. At Haas for a fresh start. Works best with clear team hierarchy and defined roles.",
        "traits": {"aggression": 65, "consistency": 65, "wet_ability": 75, "tire_mgmt": 70, "qualifying": 65, "racecraft": 65},
    },
    "albon": {
        "archetype": "The Phoenix",
        "big5": {"openness": 75, "conscientiousness": 75, "extraversion": 70, "agreeableness": 85, "neuroticism": 35},
        "driving_style": "Smooth, adaptive, excellent tire whisperer. Rebuilt career at Williams after Red Bull dropped him. Extracts remarkable results from uncompetitive machinery. One of the most liked drivers in the paddock.",
        "risk_profile": "Conservative but opportunistic. Picks moments to shine and protects the car otherwise. Survival instinct from the Red Bull experience.",
        "team_dynamics": "Beloved by mechanics and engineers. Positive energy, constructive feedback. The emotional heart of Williams. Strong relationship with Sainz as co-leader.",
        "traits": {"aggression": 40, "consistency": 75, "wet_ability": 70, "tire_mgmt": 85, "qualifying": 65, "racecraft": 70},
    },
    "hulkenberg": {
        "archetype": "The Nearly Man",
        "big5": {"openness": 55, "conscientiousness": 85, "extraversion": 55, "agreeableness": 50, "neuroticism": 40},
        "driving_style": "Experienced, consistent, technically strong. The record holder for most starts without a podium (now broken). Excellent in qualifying, sometimes fades in races. Brings invaluable experience to a new team.",
        "risk_profile": "Low risk, high consistency. In 2026 with Audi, his job is to provide a baseline and develop the car rather than take heroic risks.",
        "team_dynamics": "The veteran anchor. Provides the stability a new manufacturer needs. Professional, no drama, delivers clear data.",
        "traits": {"aggression": 45, "consistency": 75, "wet_ability": 70, "tire_mgmt": 70, "qualifying": 80, "racecraft": 60},
    },
    "bottas": {
        "archetype": "The Stoic",
        "big5": {"openness": 45, "conscientiousness": 80, "extraversion": 35, "agreeableness": 70, "neuroticism": 25},
        "driving_style": "Steady, reliable, occasionally brilliant in qualifying. The perfect wingman at Mercedes for years. In 2026, bringing that experience to the new Cadillac entry. Strong one-lap pace when confident in the car.",
        "risk_profile": "Minimal risk appetite. Races to a strategy. Rarely makes mistakes but rarely creates magic either. The embodiment of consistent points scoring.",
        "team_dynamics": "Low-ego team player. Accepted the number two role at Mercedes with grace. At Cadillac, he's the team leader and development driver.",
        "traits": {"aggression": 35, "consistency": 80, "wet_ability": 60, "tire_mgmt": 75, "qualifying": 75, "racecraft": 55},
    },
    "perez": {
        "archetype": "The Street Fighter",
        "big5": {"openness": 50, "conscientiousness": 65, "extraversion": 60, "agreeableness": 65, "neuroticism": 50},
        "driving_style": "Sunday specialist. Consistently better in races than qualifying. Exceptional tire management was his hallmark — made one-stop strategies work when nobody else could. Speed has declined with age.",
        "risk_profile": "Takes measured risks in races but qualifying has become a weakness. Form has been erratic since 2023. Brings commercial value (Mexican market) alongside driving.",
        "team_dynamics": "Experienced team player. At Cadillac for the final chapter. Brings 16 seasons of knowledge to a brand-new operation.",
        "traits": {"aggression": 50, "consistency": 55, "wet_ability": 60, "tire_mgmt": 85, "qualifying": 50, "racecraft": 70},
    },
    "alonso": {
        "archetype": "The Gladiator",
        "big5": {"openness": 65, "conscientiousness": 90, "extraversion": 55, "agreeableness": 30, "neuroticism": 35},
        "driving_style": "The most complete driver in F1 history by many accounts. Adapts to any car, any condition. In his 23rd season, still extracting the maximum. His car control in the wet remains supernatural. The 2024-2025 decline is real but the baseline was so high.",
        "risk_profile": "Fiercely competitive. Will fight for 15th like it's a race win. Has mellowed slightly with age but the fire still burns. Political operator — uses media pressure strategically.",
        "team_dynamics": "Demands respect and resources. Has outlasted multiple teammates and team principals. At Aston Martin for the long-shot championship run that hasn't materialized.",
        "traits": {"aggression": 75, "consistency": 70, "wet_ability": 90, "tire_mgmt": 80, "qualifying": 75, "racecraft": 95},
    },
    "stroll": {
        "archetype": "The Heir",
        "big5": {"openness": 45, "conscientiousness": 60, "extraversion": 35, "agreeableness": 50, "neuroticism": 40},
        "driving_style": "Inconsistent but capable of stunning results. The 2020 Turkey podium (pole in wet qualifying) showed his ceiling. Struggles with confidence and adapting to car changes. Better in the wet than dry.",
        "risk_profile": "Variable. Can produce brilliant drives or anonymous afternoons. The billionaire's son narrative overshadows genuine talent that surfaces unpredictably.",
        "team_dynamics": "Unique position — his father owns the team. This insulates him from pressure but also from the hunger that drives others. Relationship with Alonso is complex.",
        "traits": {"aggression": 55, "consistency": 50, "wet_ability": 70, "tire_mgmt": 55, "qualifying": 55, "racecraft": 55},
    },
}
