"""F1 2026 team sponsor data and economic classifications."""

TEAM_SPONSORS = {
    "mercedes": {
        "title": {"name": "Petronas", "value_m": 80, "sector": "Energy", "hq": "Malaysia", "desc": "Malaysian state oil & gas company. One of the longest-running title partnerships in F1 (since 2010)."},
        "major": [
            {"name": "Ineos", "sector": "Chemicals", "desc": "British multinational, 1/3 team owner. Jim Ratcliffe's petrochemicals empire."},
            {"name": "CrowdStrike", "sector": "Cybersecurity", "desc": "Endpoint security leader. $3B+ revenue."},
            {"name": "Microsoft", "sector": "Technology", "desc": "New for 2026. Cloud, AI, and enterprise software. Partnership includes Azure integration."},
            {"name": "UBS", "sector": "Finance", "desc": "Swiss investment bank and wealth management."},
            {"name": "Qualcomm/Snapdragon", "sector": "Semiconductors", "desc": "Mobile chipmaker. Snapdragon branding on car."},
            {"name": "AMD", "sector": "Semiconductors", "desc": "CPU/GPU manufacturer. Simulation and CFD compute."},
            {"name": "PepsiCo", "sector": "Consumer Goods", "desc": "New for 2026. Global beverage and snack company."},
            {"name": "WhatsApp", "sector": "Technology", "desc": "Meta-owned messaging platform."},
            {"name": "IWC Schaffhausen", "sector": "Luxury", "desc": "Swiss luxury watchmaker."},
        ],
    },
    "red_bull": {
        "title": {"name": "Oracle", "value_m": 110, "sector": "Technology", "hq": "USA", "desc": "Largest title deal in F1. Database, cloud infrastructure, and enterprise software. Deep technical integration with team's data systems."},
        "major": [
            {"name": "Ford", "sector": "Automotive", "desc": "New PU partner from 2026. Co-developed power unit. Return to F1 after decades."},
            {"name": "Tag Heuer", "sector": "Luxury", "desc": "LVMH luxury watchmaker. Long-standing partnership."},
            {"name": "ExxonMobil", "sector": "Energy", "desc": "Fuel and lubricant technology partner."},
            {"name": "Siemens", "sector": "Industrial", "desc": "Engineering technology. Simulation and digital twin tools."},
            {"name": "AT&T", "sector": "Telecommunications", "desc": "Connectivity and communications partner."},
            {"name": "Visa", "sector": "Finance", "desc": "Payment network. Also sponsors Racing Bulls."},
            {"name": "Hard Rock", "sector": "Hospitality", "desc": "Entertainment and hospitality brand."},
            {"name": "Castore", "sector": "Apparel", "desc": "British sportswear brand. Teamwear supplier."},
        ],
    },
    "ferrari": {
        "title": {"name": "HP", "value_m": 100, "sector": "Technology", "hq": "USA", "desc": "Computer hardware and printing. Second-largest title deal. HP branding replaced AWS."},
        "major": [
            {"name": "Shell", "sector": "Energy", "desc": "Fuel and lubricant partner since 1929. The longest-running partnership in F1."},
            {"name": "Ray-Ban", "sector": "Consumer", "desc": "Meta/EssilorLuxottica eyewear brand."},
            {"name": "Richard Mille", "sector": "Luxury", "desc": "Ultra-luxury watchmaker. Drivers wear RM watches."},
            {"name": "Puma", "sector": "Apparel", "desc": "Sportswear and race suit supplier."},
            {"name": "IBM", "sector": "Technology", "desc": "Enterprise computing and AI."},
            {"name": "UniCredit", "sector": "Finance", "desc": "Italian banking group."},
            {"name": "Peroni", "sector": "Beverages", "desc": "Italian beer brand."},
            {"name": "Ceva Logistics", "sector": "Logistics", "desc": "Global logistics and freight management."},
        ],
    },
    "mclaren": {
        "title": {"name": "Mastercard", "value_m": 90, "sector": "Finance", "hq": "USA", "desc": "New for 2026. Global payment network. Return to F1 after the infamous 1997 deal."},
        "major": [
            {"name": "Google/Chrome", "sector": "Technology", "desc": "Search, cloud, and browser branding."},
            {"name": "Dell Technologies", "sector": "Technology", "desc": "Computer hardware and enterprise IT."},
            {"name": "Deloitte", "sector": "Consulting", "desc": "Big Four professional services."},
            {"name": "Goldman Sachs", "sector": "Finance", "desc": "Investment banking. Significant financial partner."},
            {"name": "Cisco", "sector": "Technology", "desc": "Networking and communications equipment."},
            {"name": "OKX", "sector": "Crypto", "desc": "Cryptocurrency exchange. Major livery presence."},
            {"name": "Monster Energy", "sector": "Beverages", "desc": "Energy drink brand."},
            {"name": "Hilton", "sector": "Hospitality", "desc": "Hotel chain. Travel and hospitality partner."},
            {"name": "LEGO", "sector": "Consumer", "desc": "Toy manufacturer. Fan engagement partnership."},
            {"name": "Groq", "sector": "AI Hardware", "desc": "AI inference chip company. LPU technology."},
        ],
    },
    "aston_martin": {
        "title": {"name": "Aramco", "value_m": 75, "sector": "Energy", "hq": "Saudi Arabia", "desc": "Saudi Aramco — world's largest oil company by revenue. Major strategic investment in team."},
        "major": [
            {"name": "Honda", "sector": "Automotive", "desc": "New PU supplier from 2026. Return to works engine partnership."},
            {"name": "Cognizant", "sector": "Technology", "desc": "IT consulting and digital transformation."},
            {"name": "JCB", "sector": "Industrial", "desc": "Construction equipment manufacturer."},
            {"name": "TikTok", "sector": "Technology", "desc": "Social media platform. Content partnership."},
            {"name": "Breitling", "sector": "Luxury", "desc": "New for 2026. Swiss luxury watchmaker."},
            {"name": "CoreWeave", "sector": "Cloud/AI", "desc": "GPU cloud computing. AI infrastructure."},
            {"name": "Coinbase", "sector": "Crypto", "desc": "Cryptocurrency exchange."},
        ],
    },
    "alpine": {
        "title": {"name": "BWT", "value_m": 40, "sector": "Water Technology", "hq": "Austria", "desc": "Best Water Technology — water treatment and purification. The pink livery source."},
        "major": [
            {"name": "Microsoft", "sector": "Technology", "desc": "Cloud and enterprise technology partner."},
            {"name": "Boeing", "sector": "Aerospace", "desc": "Aerospace manufacturer. Engineering collaboration."},
            {"name": "Qatar Airways", "sector": "Aviation", "desc": "Airline partner."},
            {"name": "MSC Cruises", "sector": "Travel", "desc": "Cruise line operator."},
            {"name": "eToro", "sector": "Finance", "desc": "New for 2026. Social trading platform."},
        ],
    },
    "williams": {
        "title": {"name": "Atlassian", "value_m": 35, "sector": "Technology", "hq": "Australia", "desc": "Enterprise collaboration software (Jira, Confluence). Partnership reflects team's digital transformation."},
        "major": [
            {"name": "Gulf Oil", "sector": "Energy", "desc": "Iconic Gulf livery. Lubricant and fuel technology."},
            {"name": "Duracell", "sector": "Consumer", "desc": "Battery brand. Berkshire Hathaway subsidiary."},
            {"name": "Komatsu", "sector": "Industrial", "desc": "Japanese heavy equipment manufacturer."},
            {"name": "Kraken", "sector": "Crypto", "desc": "Cryptocurrency exchange."},
            {"name": "Barclays", "sector": "Finance", "desc": "New for 2026. British banking group."},
            {"name": "Claude", "sector": "AI", "desc": "Anthropic's AI assistant. Technology and engineering partnership."},
            {"name": "Zoox", "sector": "Autonomous Vehicles", "desc": "Amazon-owned self-driving car company."},
        ],
    },
    "rb": {
        "title": {"name": "Visa/Cash App", "value_m": 50, "sector": "Finance", "hq": "USA", "desc": "Dual title sponsor — Visa (payment network) and Cash App (Block/Square's payment app)."},
        "major": [
            {"name": "Ford", "sector": "Automotive", "desc": "Shared PU partnership with Red Bull."},
            {"name": "Hugo Boss", "sector": "Fashion", "desc": "Premium fashion brand. Teamwear."},
            {"name": "Tudor", "sector": "Luxury", "desc": "Rolex subsidiary watchmaker."},
            {"name": "Randstad", "sector": "Staffing", "desc": "Dutch employment agency."},
        ],
    },
    "haas": {
        "title": {"name": "Toyota Gazoo Racing", "value_m": 30, "sector": "Automotive", "hq": "Japan", "desc": "Technical partnership includes manufacturing support and engineering collaboration. TGR branding."},
        "major": [
            {"name": "Haas Automation", "sector": "Manufacturing", "desc": "CNC machine tool builder. Team owner Gene Haas's company."},
            {"name": "MGM Rewards", "sector": "Hospitality", "desc": "Casino and entertainment loyalty program."},
            {"name": "UChicago Medicine", "sector": "Healthcare", "desc": "Academic medical center partnership."},
        ],
    },
    "audi": {
        "title": {"name": "Revolut", "value_m": 75, "sector": "Fintech", "hq": "UK", "desc": "Digital banking platform. One of the largest fintech companies in Europe."},
        "major": [
            {"name": "Audi", "sector": "Automotive", "desc": "Volkswagen Group brand. Factory team with own PU development."},
            {"name": "BP/Castrol", "sector": "Energy", "desc": "Fuel and lubricant partner."},
            {"name": "Adidas", "sector": "Apparel", "desc": "Sportswear brand. Teamwear supplier."},
            {"name": "Gillette", "sector": "Consumer", "desc": "P&G grooming brand."},
            {"name": "ElevenLabs", "sector": "AI", "desc": "AI voice synthesis company."},
        ],
    },
    "cadillac": {
        "title": None,
        "major": [
            {"name": "General Motors", "sector": "Automotive", "desc": "Parent company. Cadillac brand. GM PU planned for 2028."},
            {"name": "TWG AI", "sector": "AI", "desc": "Team owner's AI venture."},
            {"name": "Jim Beam", "sector": "Beverages", "desc": "Bourbon whiskey brand. Beam Suntory."},
            {"name": "Tommy Hilfiger", "sector": "Fashion", "desc": "American fashion brand."},
            {"name": "Core Scientific", "sector": "Technology", "desc": "Bitcoin mining and data center company."},
        ],
    },
}

SECTOR_COLORS = {
    "Technology": "#58a6ff",
    "Energy": "#d29922",
    "Finance": "#3fb950",
    "Fintech": "#3fb950",
    "Automotive": "#f85149",
    "Luxury": "#bb9af7",
    "Consumer": "#ff8700",
    "Consumer Goods": "#ff8700",
    "Apparel": "#ff8700",
    "Beverages": "#ff8700",
    "Aerospace": "#6692ff",
    "Industrial": "#8b949e",
    "Manufacturing": "#8b949e",
    "Consulting": "#58a6ff",
    "Cybersecurity": "#f85149",
    "Crypto": "#d29922",
    "Semiconductors": "#bb9af7",
    "Hospitality": "#73daca",
    "Travel": "#73daca",
    "Aviation": "#73daca",
    "Fashion": "#bb9af7",
    "Healthcare": "#3fb950",
    "AI": "#58a6ff",
    "AI Hardware": "#58a6ff",
    "Cloud/AI": "#58a6ff",
    "Autonomous Vehicles": "#58a6ff",
    "Staffing": "#8b949e",
    "Logistics": "#8b949e",
    "Chemicals": "#d29922",
    "Water Technology": "#73daca",
    "Telecommunications": "#6692ff",
}
